codecov:
  branch: dev
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1
    patch:
      default:
        target: auto
        threshold: 10
comment: false

# To make partial tests possible,
# we need to carry forward.
flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: full-suite
      paths:
        - ".*"
      carryforward: true
